Repository it-minds/itm_no-mindster-tv, pull requests merged in 2023-09, with the labels that each got.

#23 build: dockerize nextjs app
  .env.production
  CONTRIBUTING.md
  Dockerfile.prod
  next.config.js
  package-lock.json
Labels: build

#14 Create test pipeline
  .github/workflows/BuildAndTest.yml
  Dockerfile.test
Labels: ci

#26 feat: add iFrame from Yr to the main page
  src/app/page.tsx
Labels: feat

#27 chore: setup NextUI on top of tailwindcss
  .eslintrc.json
  .prettierrc.json
  CONTRIBUTING.md
  package-lock.json
  package.json
  prettier.config.js
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/providers.spec.tsx
  src/app/providers.tsx
  tailwind.config.js
  tailwind.config.ts
Labels: chore

#29 feat: create simple frame for displaying modules
  .storybook/preview.ts
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/app/page.tsx
  src/commons/assets/logo/logo-white.png
  src/commons/assets/shapes/circle-yellow.png
  src/commons/assets/shapes/hexagon-yellow.png
  src/commons/assets/shapes/square-yellow.png
  src/commons/assets/shapes/triangle-blue.png
  src/commons/frame/frame.spec.tsx
  src/commons/frame/frame.stories.tsx
  src/commons/frame/frame.tsx
  tailwind.config.js
  tsconfig.json
Labels: feat

#34 feat: add countdown module temporarily for fall kickoff
  src/app/page.tsx
Labels: feat

#37 feat: implement clock module
  package-lock.json
  package.json
  src/app/page.tsx
  src/commons/components/frame/frame.spec.tsx
  src/commons/components/frame/frame.stories.tsx
  src/commons/components/frame/frame.tsx
  src/commons/components/framed/framed.spec.tsx
  src/commons/components/framed/framed.stories.tsx
  src/commons/components/framed/framed.tsx
  src/commons/components/iframe-module/iframe-module.spec.tsx
  src/commons/components/iframe-module/iframe-module.tsx
  src/commons/helpers/datetime/datetime.spec.ts
  src/commons/helpers/datetime/datetime.ts
  src/commons/hooks/adaptive-text/use-adaptive-text.spec.tsx
  src/commons/hooks/adaptive-text/use-adaptive-text.ts
  src/commons/hooks/resize-observer/use-resize-observer.spec.tsx
  src/commons/hooks/resize-observer/use-resize-observer.ts
  src/modules/clock/clock-module.hook.spec.ts
  src/modules/clock/clock-module.hook.ts
  src/modules/clock/clock-module.spec.tsx
  src/modules/clock/clock-module.stories.tsx
  src/modules/clock/clock-module.tsx
  src/modules/module.d.ts
  src/stories/Button.spec.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.spec.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.spec.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  tailwind.config.js
Labels: feat

#40 refactor: move chris to new position
  src/app/page.tsx
Labels: refactor
